FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./

# rebuild node-sass
RUN yarn add node-sass

RUN yarn install

COPY . .


RUN yarn build:staging

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
